// ============================================================
// Sound Data Definitions
// TypeScript port of sounds.c / sounds.h
// All SFX identifiers and metadata tables
// ============================================================

// ---- SFX identifiers ----
export enum Sfx {
  None = 0,
  pistol,
  shotgn,
  sgcock,
  dshtgn,
  dbopn,
  dbcls,
  dbload,
  plasma,
  bfg,
  sawup,
  sawidl,
  sawful,
  sawhit,
  rlaunc,
  rxplod,
  firsht,
  firxpl,
  pstart,
  pstop,
  doropn,
  dorcls,
  stnmov,
  swtchn,
  swtchx,
  plpain,
  dmpain,
  popain,
  vipain,
  mnpain,
  pepain,
  slop,
  itemup,
  wpnup,
  oof,
  telept,
  posit1,
  posit2,
  posit3,
  bgsit1,
  bgsit2,
  sgtsit,
  cacsit,
  brssit,
  cybsit,
  spisit,
  bspsit,
  kntsit,
  vilsit,
  mansit,
  pesit,
  sklatk,
  sgtatk,
  skepch,
  vilatk,
  claw,
  skeswg,
  pldeth,
  pdiehi,
  podth1,
  podth2,
  podth3,
  bgdth1,
  bgdth2,
  sgtdth,
  cacdth,
  skldth,
  brsdth,
  cybdth,
  spidth,
  bspdth,
  vildth,
  kntdth,
  pedth,
  skedth,
  posact,
  bgact,
  dmact,
  bspact,
  bspwlk,
  vilact,
  noway,
  barexp,
  punch,
  hoof,
  metal,
  chgun,
  tink,
  bdopn,
  bdcls,
  itmbk,
  flame,
  flamst,
  getpow,
  bospit,
  boscub,
  bossit,
  bospn,
  bosdth,
  manatk,
  mandth,
  sssit,
  ssdth,
  keenpn,
  keendt,
  skeact,
  skesit,
  skeatk,
  radio,
  NUMSFX,
}

// ---- SFX info structure ----
export interface SfxInfo {
  /** Lump name (without DS prefix) */
  name: string;
  /** Only one instance at a time */
  singularity: boolean;
  /** Priority (higher = more important to keep playing) */
  priority: number;
  /** Link to another SFX (alias — e.g. chaingun → pistol) */
  link: Sfx | null;
  /** Pitch offset if linked */
  pitch: number;
  /** Volume offset if linked */
  volume: number;
}

// ---- SFX data table (from sounds.c) ----
export const S_sfx: SfxInfo[] = [
  // S_sfx[0] needs to be a dummy for odd reasons.
  { name: 'none',   singularity: false,  priority: 0,   link: null, pitch: -1, volume: -1 },

  { name: 'pistol', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'shotgn', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'sgcock', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'dshtgn', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'dbopn',  singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'dbcls',  singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'dbload', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'plasma', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'bfg',    singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'sawup',  singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'sawidl', singularity: false,  priority: 118, link: null, pitch: -1, volume: -1 },
  { name: 'sawful', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'sawhit', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'rlaunc', singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'rxplod', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'firsht', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'firxpl', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'pstart', singularity: false,  priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'pstop',  singularity: false,  priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'doropn', singularity: false,  priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'dorcls', singularity: false,  priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'stnmov', singularity: false,  priority: 119, link: null, pitch: -1, volume: -1 },
  { name: 'swtchn', singularity: false,  priority: 78,  link: null, pitch: -1, volume: -1 },
  { name: 'swtchx', singularity: false,  priority: 78,  link: null, pitch: -1, volume: -1 },
  { name: 'plpain', singularity: false,  priority: 96,  link: null, pitch: -1, volume: -1 },
  { name: 'dmpain', singularity: false,  priority: 96,  link: null, pitch: -1, volume: -1 },
  { name: 'popain', singularity: false,  priority: 96,  link: null, pitch: -1, volume: -1 },
  { name: 'vipain', singularity: false,  priority: 96,  link: null, pitch: -1, volume: -1 },
  { name: 'mnpain', singularity: false,  priority: 96,  link: null, pitch: -1, volume: -1 },
  { name: 'pepain', singularity: false,  priority: 96,  link: null, pitch: -1, volume: -1 },
  { name: 'slop',   singularity: false,  priority: 78,  link: null, pitch: -1, volume: -1 },
  { name: 'itemup', singularity: true,   priority: 78,  link: null, pitch: -1, volume: -1 },
  { name: 'wpnup',  singularity: true,   priority: 78,  link: null, pitch: -1, volume: -1 },
  { name: 'oof',    singularity: false,  priority: 96,  link: null, pitch: -1, volume: -1 },
  { name: 'telept', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'posit1', singularity: true,   priority: 98,  link: null, pitch: -1, volume: -1 },
  { name: 'posit2', singularity: true,   priority: 98,  link: null, pitch: -1, volume: -1 },
  { name: 'posit3', singularity: true,   priority: 98,  link: null, pitch: -1, volume: -1 },
  { name: 'bgsit1', singularity: true,   priority: 98,  link: null, pitch: -1, volume: -1 },
  { name: 'bgsit2', singularity: true,   priority: 98,  link: null, pitch: -1, volume: -1 },
  { name: 'sgtsit', singularity: true,   priority: 98,  link: null, pitch: -1, volume: -1 },
  { name: 'cacsit', singularity: true,   priority: 98,  link: null, pitch: -1, volume: -1 },
  { name: 'brssit', singularity: true,   priority: 94,  link: null, pitch: -1, volume: -1 },
  { name: 'cybsit', singularity: true,   priority: 92,  link: null, pitch: -1, volume: -1 },
  { name: 'spisit', singularity: true,   priority: 90,  link: null, pitch: -1, volume: -1 },
  { name: 'bspsit', singularity: true,   priority: 90,  link: null, pitch: -1, volume: -1 },
  { name: 'kntsit', singularity: true,   priority: 90,  link: null, pitch: -1, volume: -1 },
  { name: 'vilsit', singularity: true,   priority: 90,  link: null, pitch: -1, volume: -1 },
  { name: 'mansit', singularity: true,   priority: 90,  link: null, pitch: -1, volume: -1 },
  { name: 'pesit',  singularity: true,   priority: 90,  link: null, pitch: -1, volume: -1 },
  { name: 'sklatk', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'sgtatk', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'skepch', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'vilatk', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'claw',   singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'skeswg', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'pldeth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'pdiehi', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'podth1', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'podth2', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'podth3', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'bgdth1', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'bgdth2', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'sgtdth', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'cacdth', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'skldth', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'brsdth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'cybdth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'spidth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'bspdth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'vildth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'kntdth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'pedth',  singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'skedth', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'posact', singularity: true,   priority: 120, link: null, pitch: -1, volume: -1 },
  { name: 'bgact',  singularity: true,   priority: 120, link: null, pitch: -1, volume: -1 },
  { name: 'dmact',  singularity: true,   priority: 120, link: null, pitch: -1, volume: -1 },
  { name: 'bspact', singularity: true,   priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'bspwlk', singularity: true,   priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'vilact', singularity: true,   priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'noway',  singularity: false,  priority: 78,  link: null, pitch: -1, volume: -1 },
  { name: 'barexp', singularity: false,  priority: 60,  link: null, pitch: -1, volume: -1 },
  { name: 'punch',  singularity: false,  priority: 64,  link: null, pitch: -1, volume: -1 },
  { name: 'hoof',   singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'metal',  singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  // chgun links to pistol with pitch=150, volume=0
  { name: 'chgun',  singularity: false,  priority: 64,  link: Sfx.pistol, pitch: 150, volume: 0 },
  { name: 'tink',   singularity: false,  priority: 60,  link: null, pitch: -1, volume: -1 },
  { name: 'bdopn',  singularity: false,  priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'bdcls',  singularity: false,  priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'itmbk',  singularity: false,  priority: 100, link: null, pitch: -1, volume: -1 },
  { name: 'flame',  singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'flamst', singularity: false,  priority: 32,  link: null, pitch: -1, volume: -1 },
  { name: 'getpow', singularity: false,  priority: 60,  link: null, pitch: -1, volume: -1 },
  { name: 'bospit', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'boscub', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'bossit', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'bospn',  singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'bosdth', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'manatk', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'mandth', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'sssit',  singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'ssdth',  singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'keenpn', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'keendt', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'skeact', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'skesit', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'skeatk', singularity: false,  priority: 70,  link: null, pitch: -1, volume: -1 },
  { name: 'radio',  singularity: false,  priority: 60,  link: null, pitch: -1, volume: -1 },
];

// ============================================================
// Music Definitions (from sounds.c / sounds.h)
// ============================================================

export enum Music {
  None = 0,
  e1m1, e1m2, e1m3, e1m4, e1m5, e1m6, e1m7, e1m8, e1m9,
  e2m1, e2m2, e2m3, e2m4, e2m5, e2m6, e2m7, e2m8, e2m9,
  e3m1, e3m2, e3m3, e3m4, e3m5, e3m6, e3m7, e3m8, e3m9,
  inter, intro, bunny, victor, introa,
  // DOOM II
  runnin, stalks, countd, betwee, doom, the_da, shawn, ddtblu,
  in_cit, dead, stlks2, theda2, doom2, ddtbl2, runni2, dead2,
  stlks3, romero, shawn2, messag, count2, ddtbl3, ampie, theda3,
  adrian, messg2, romer2, tense, shawn3, openin, evil, ultima,
  read_m, dm2ttl, dm2int,
  NUMMUSIC,
}

export interface MusicInfo {
  /** Lump name (without D_ prefix) */
  name: string;
}

/** Music data table — index by Music enum */
export const S_music: MusicInfo[] = [
  { name: '' },       // mus_None
  { name: 'e1m1' },  { name: 'e1m2' },  { name: 'e1m3' },
  { name: 'e1m4' },  { name: 'e1m5' },  { name: 'e1m6' },
  { name: 'e1m7' },  { name: 'e1m8' },  { name: 'e1m9' },
  { name: 'e2m1' },  { name: 'e2m2' },  { name: 'e2m3' },
  { name: 'e2m4' },  { name: 'e2m5' },  { name: 'e2m6' },
  { name: 'e2m7' },  { name: 'e2m8' },  { name: 'e2m9' },
  { name: 'e3m1' },  { name: 'e3m2' },  { name: 'e3m3' },
  { name: 'e3m4' },  { name: 'e3m5' },  { name: 'e3m6' },
  { name: 'e3m7' },  { name: 'e3m8' },  { name: 'e3m9' },
  { name: 'inter' }, { name: 'intro' }, { name: 'bunny' },
  { name: 'victor' }, { name: 'introa' },
  // DOOM II
  { name: 'runnin' }, { name: 'stalks' }, { name: 'countd' },
  { name: 'betwee' }, { name: 'doom' },   { name: 'the_da' },
  { name: 'shawn' },  { name: 'ddtblu' }, { name: 'in_cit' },
  { name: 'dead' },   { name: 'stlks2' }, { name: 'theda2' },
  { name: 'doom2' },  { name: 'ddtbl2' }, { name: 'runni2' },
  { name: 'dead2' },  { name: 'stlks3' }, { name: 'romero' },
  { name: 'shawn2' }, { name: 'messag' }, { name: 'count2' },
  { name: 'ddtbl3' }, { name: 'ampie' },  { name: 'theda3' },
  { name: 'adrian' }, { name: 'messg2' }, { name: 'romer2' },
  { name: 'tense' },  { name: 'shawn3' }, { name: 'openin' },
  { name: 'evil' },   { name: 'ultima' }, { name: 'read_m' },
  { name: 'dm2ttl' }, { name: 'dm2int' },
];
